[job]
title = "SSENSE"
group_by = "item_group_id"
separator = "\t"

[[job.field]]
name = "item_group_id"
rename = "groupId"

[[job.field]]
name = "title"

[[job.field]]
name = "price"

[[job.field]]
name = "sale_price"
rename = "salePrice"
