[job]
title = "Simple Validation"
group_by = ""

[[job.field]]
name = "item_group_id"
rename = "group_id"

[[job.field]]
name = "id"

[[job.field]]
name = "name"
validation = ["non_empty"]

[[job.field]]
name = "price"

[[job.field]]
name = "gender"
validation = ["one_of:m,f"]

[[job.field]]
name = "ident"
validation = ["min_length:2"]
