title = "Simple Validation"

[[columns]]
name = "item_group_id"
rename = "group_id"

[[columns]]
name = "id"

[[columns]]
name = "name"
validation = ["non_empty"]

[[columns]]
name = "price"

[[columns]]
name = "gender"
validation = ["one_of:m,f"]

[[columns]]
name = "ident"
validation = ["min_length:2"]
