[job]
title = "Simple Validation"
group_by = ""

[[job.field]]
name = "item_group_id"
rename = "group_id"

[[job.field]]
name = "id"

[[job.field]]
name = "name"

[[job.field]]
name = "gender"

[[job.field]]
name = "ident"
validation = ["min_length:2"]
